import Head from 'next/head'
import Image from 'next/image'
import AlignItems from '../lib/AlignItems'
import Button from '../lib/Button'
import Footer from '../lib/Footer'
import styles from '../styles/Home.module.css'
import logo from '../public/sg-banner-logo.png'
import PostThumbNail from '../lib/PostThumbNail'
import { useRouter } from 'next/router'
import { createClient } from 'contentful'

export async function getStaticProps(){
  const client = createClient({
    space:process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID,
    accessToken:process.env.NEXT_PUBLIC_CONTENTFUL_ACCESS_KEY,
  })
  const res = await client.getEntries({
    content_type:'sgPage'
  })
  return{
    props:{
      sgPosts:res.items
    }
  }
}

export default function Home({sgPosts}) {
  const router = useRouter()
  console.log(sgPosts)
  return (
    <div className={styles.container}>
      <Head>
        <title>SEIRYO GROUND</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{display: 'flex', alignItems: 'flex-start', gap:'1.5em'}}>
        <section
          style={{
            maxWidth: '300px',
            minWidth: '250px',
            position: 'sticky',
            top: '20px'
          }}
        >
          <Image src={logo} width="290" height="100"/>
          <p>外を歩き回り、今までいって良かった場所をまとめました。</p>
          <AlignItems>
            <Button onClick={()=>router.push('/about')}>清涼広場について</Button>
          </AlignItems>
        </section>
        <section
          className="grid-1fr-1fr-1fr-1fr-1fr"
        >
          {sgPosts.map(data =>{
            return(
              <PostThumbNail
                key={data.sys.id}
                slug={data.fields.slug}
                title={data.fields.title}
                type={data.fields.type}
                date={data.fields.date.split('T')[0]}
              />
            )
          })}
        </section>
      </main>

      <Footer></Footer>
    </div>
  )
}
